#! /usr/bin/php
<?php
$siteRoot = dirname(dirname(__DIR__));
require $siteRoot.'/vendor/autoload.php';

$handler = new Phpple\GitWatcher\HookHandler($siteRoot);
$ret = $handler->preCommit();
if (!$ret) {
    echo 'GitWatcher check failed!'.PHP_EOL;
    exit(1);
} else {
    echo 'GitWatcher check passed!'.PHP_EOL;
}
